### ISSUE TITLE
HTML output from "istanbul cover" and "istanbul report" is different

### ISSUE THREAD

**Issue by bennyn** [istanbuljs/istanbuljs#166]
I have code written in TypeScript which I transpile to JavaScript using the TypeScript compiler (`tsc`). The output is generated together with source maps (`.js.map`).

I am using **istanbul v1.1.0-alpha.1** to instrument my code and to get a code coverage report in HTML format. Here is the command I use to generate the report:

```bash
istanbul cover ./node_modules/jasmine/bin/jasmine.js --print detail --report html --verbose
```

The generated output is great as I am getting the coverage report from my transpiled JavaScript code which is remapped to TypeScript:

![image](https://user-images.githubusercontent.com/469989/39924218-3990f0d4-5527-11e8-97ee-d62493e457e2.png)

In my case the `istanbul cover` command creates a `coverage/node` directory which contains the HTML report as well as a `coverage.raw.json` file. 

I tried now to create another report from the `coverage.raw.json` file by using `istanbul cover`. Here is the command I used to accomplish that:

```bash
istanbul report --root ./coverage/node --dir ./coverage/report
```

The result was surprising because I got a coverage report but it does not remap to my TypeScript files. Instead it shows me the coverage for the transpiled JavaScript files:

![image](https://user-images.githubusercontent.com/469989/39924394-de21eb3a-5527-11e8-9017-82ec424def50.png)

That's very confusing and I would like to know why that is the case. Can anyone help me to find out?

Here is my `.istanbul.yml`:

```yml
verbose: true
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
instrumentation:
    excludes: ['**/*test.*.js']
reporting:
    print: summary
    reports:
        - html
    dir: ./coverage/node
```

Maybe the `coverage.raw.json` helps to debug my problem: [coverage.raw.json.zip](https://github.com/istanbuljs/istanbuljs/files/1995292/coverage.raw.json.zip)
